// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clicks.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const countClicks = `-- name: CountClicks :one
SELECT
    count(*)
FROM
    clicks
WHERE
    url_id = $1
`

func (q *Queries) CountClicks(ctx context.Context, urlID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClicks, urlID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const storeClick = `-- name: StoreClick :exec
INSERT INTO
    clicks (id, url_id, ip, clicked_at)
VALUES
    ($1, $2, $3, $4)
`

type StoreClickParams struct {
	ID        uuid.UUID
	UrlID     uuid.UUID
	Ip        string
	ClickedAt int64
}

func (q *Queries) StoreClick(ctx context.Context, arg StoreClickParams) error {
	_, err := q.db.ExecContext(ctx, storeClick,
		arg.ID,
		arg.UrlID,
		arg.Ip,
		arg.ClickedAt,
	)
	return err
}
